### ISSUE TITLE
Subscription name contains '/' will cause a 404 error

### ISSUE THREAD

**Issue by zzl221000** [apache/pulsar-manager#210]
I can access it normally after url encoding.
`/management/subscriptions/persistent/public/hbase/alter_id/persistent%3a%2f%2fpublic%2fhbase%2falter_id_xjk/subscription?topTab=backlogOperation&leftTab=skip`

**Comment by tuteng** [comment]
persistent://public/hbase/alter_id_xjk  

I am not sure where this subscription name was generated, this is a topic name.
The meaning of each field in this path is as 

* `public` is tenant name
* `hbase` is namespace name
* `alter_id_xjk` is topic name

The correct http request should look like this, if `alter_id_xjk` is subscription name:
```
curl -v http://ip:port/management/subscriptions/persistent/public/hbase/alter_id_xjk/subscriptions
```
@zzl221000

**Comment by zzl221000** [comment]
This subscription name is generated by an operation error when using the java client. 
An error will occur as long as the '/' is included in the subscription name.
![image](https://user-images.githubusercontent.com/14102425/68849301-c4bdda80-070c-11ea-8f1b-e53ae26391e5.png)

@tuteng

**Comment by tuteng** [comment]
I think your client used an irregular subscription name when creating the connection. The broker did not check this name. Can you show me your client code? The subscription name should look like this:
```
Consumer consumer = client.newConsumer()
        .topic("my-topic")
        .subscriptionName("subscription-name")
        .subscribe();
```
Special characters such as colon slash cannot appear in `subscription-name`

**Comment by zzl221000** [comment]
As you said, my client uses specialcharacters in the subscription name.
```
String topic="persistent://public/default/my-topic"
Consumer consumer = client.newConsumer()
        .topic(topic)
        .subscriptionName(topic)
        .subscribe();
```
The broker allows this,  whether to consider compatibility with this situation?
@tuteng

**Comment by tuteng** [comment]
I think the broker should do a check. The subscription name is not standard. The topic name is allowed to be written like this because the full path contains tenants, namespaces, etc. The real topic name is my-topic, but the subscription name should not allow these contents to appear. The presence of special characters in the subscription name will make the system extremely complex and many rest API at the back end will make it unavailable. In fact, this 404 was not thrown by pulsar-manager's back-end service. It was thrown by pulsar's rest service. Since there was no specification check on the subscription name, although the subscription name was generated, its rest service could not normally handle it. You can verify it by using the following methods:

```
bin/pulsar-client consume -s persistent://public/default/test5 -n 0 persistent://public/default/test5
curl -v -X DELETE http://localhost:8080/admin/v2/persistent/public/default/test5/subscription/persistent://public/default/test5
```
`://` and `/` are characters with special meaning in http protocol, so it is difficult to verify the subscription name.

**Comment by tuteng** [comment]
I think we can close the issue first now, and we'd better follow up on this issue in pulsar's repository. @zzl221000
